version: '3'

services:
  app:
    container_name: "lanchonete_products_ms"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/lanchonete_products
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: lanchonete_products
    ports:
      - "5432:5432"